### ISSUE TITLE
qr功能无法使用

### ISSUE THREAD

**Issue by zhengrong5600** [Xtao-Labs/PagerMaid-Modify#127]
### 实际发生了什么？
无法使用qr功能
### 额外信息（日志、报错等）
qr功能报错

**Comment by zhengrong5600** [comment]
@zhengrong5600 对，一直无法使用这个参数（qr）

**Comment by xtaodada** [comment]
@zhengrong5600 请查看程序控制台日志输出，zbar 软件包用于处理二维码信息，如您没有安装此软件包，将无法使用二维码相关功能。
