### ISSUE TITLE
-s 添加贴纸至贴纸包时可以同时选择 emoji 和 帖子包名称

### ISSUE THREAD

**Issue by scatking** [Xtao-Labs/PagerMaid-Modify#139]
### 这是一个什么样的功能？
使用-s 添加贴纸至贴纸包时可以使用形如 `-s 🐣 to xxxx` 的指令同时指定emoji和目标贴纸包
### 这个 feature 可以干什么？
使得-s 指令更加全面,方便需要同时设定emoji和贴纸包的情景
### 额外描述
https://github.com/Xtao-Labs/PagerMaid-Modify/blob/173c9b8db714349b539da294283d9db8438eb0ba/pagermaid/modules/sticker.py#L260

**Comment by sam01101** [comment]
接了，你真幸运
