### ISSUE TITLE
Docker正常安装后，日志显示运行正常，但是发送命令无响应。

### ISSUE THREAD

**Issue by justhy** [Xtao-Labs/PagerMaid-Modify#142]
### BUG 发生地址
输入命令，没有任何反应。

### 预期是什么？
输入预制命令后，会有反应，能正常试用

### 实际发生了什么？
Docker安装后，日志中显示正常运行，但是发出命令没有任何响应。

### 额外信息（日志、报错等）
![Snipaste_2021-10-31_23-08-27](https://user-images.githubusercontent.com/17880968/139590029-bb77cfbe-1b06-4c7e-8fa1-500ce0048538.png)

**Comment by justhy** [comment]
突然可以使用了！

**Comment by xtaodada** [comment]
可能程序还未启动完成，请开启后稍等几分钟。
