### ISSUE TITLE
docker执行命令无效？

### ISSUE THREAD

**Issue by PS0123456** [Xtao-Labs/PagerMaid-Modify#151]
### 实际发生了什么？
今天突然发现Bot输入命令无效，比如-dme
docker restart pagermaid
docker exec -it pagermaid bash utils/docker-config.sh
然后就没任何反应。。。包括授权什么的？
-输入任何命令机器人也无效果

**Comment by xtaodada** [comment]
@PS0123456 由于 Telegram 强制注销了部分用户的部分客户端，请删除映射目录下的 pagermaid.session 以及 install.lock 然后运行 docker exec -it pagermaid bash utils/docker-config.sh 重新登录。

**Comment by PS0123456** [comment]
![image](https://user-images.githubusercontent.com/13433663/144195900-8d745f15-9653-4286-8320-6059cc641bba.png)
update app tp log in?

**Comment by sam01101** [comment]
> ![image](https://user-images.githubusercontent.com/13433663/144195900-8d745f15-9653-4286-8320-6059cc641bba.png) update app tp log in?

请先更新 `telethon` 然后再次登录

**Comment by PS0123456** [comment]
> > ![image](https://user-images.githubusercontent.com/13433663/144195900-8d745f15-9653-4286-8320-6059cc641bba.png) update app tp log in?
> 
> 请先更新 `telethon` 然后再次登录

感謝，終於成功了
