### ISSUE TITLE
关于docker环境下，某些部分插件安装失败的问题

### ISSUE THREAD

**Issue by ixinshang** [Xtao-Labs/PagerMaid-Modify#162]
### BUG 发生地址
环境：ARM64 
镜像：latest
网络环境：路由器V2透明代理

### 预期是什么？
-apt install dme 应该可以正常安装

### 实际发生了什么？
安装失败

### 额外信息（日志、报错等）
INFO [2021-12-30 13:48:26] [pagermaid] 将平台检测为“linux，进入PagerMaid的早期加载过程。
INFO [2021-12-30 13:48:28] [pagermaid] 设置用户标识成功。 SS(7777777777)
INFO [2021-12-30 13:48:31] [pagermaid] 加载内置模块: account, avoid, captions, clock, external, fun, help, message, plugin, prune, qr, sb, status, sticker, system, update
INFO [2021-12-30 13:48:31] [pagermaid] 加载插件: groupindex, keyword, paolu, yvlu
INFO [2021-12-30 13:48:33] [pagermaid] Web 界面已禁用。
INFO [2021-12-30 13:48:39] [pagermaid] PagerMaid-Modify 已启动，在任何聊天中输入 -help 以获得帮助消息。
INFO [2021-12-30 13:53:35] [pagermaid] 安装成功 : mjx

INFO [2021-12-30 13:53:42] [pagermaid] 将平台检测为“linux，进入PagerMaid的早期加载过程。
INFO [2021-12-30 13:53:44] [pagermaid] 设置用户标识成功。 SS(7777777777)
INFO [2021-12-30 13:53:48] [pagermaid] 加载内置模块: account, avoid, captions, clock, external, fun, help, message, plugin, prune, qr, sb, status, sticker, system, update
INFO [2021-12-30 13:53:48] [pagermaid] 加载插件: groupindex, keyword, mjx, paolu, yvlu
INFO [2021-12-30 13:53:49] [pagermaid] Web 界面已禁用。
INFO [2021-12-30 13:53:55] [pagermaid] PagerMaid-Modify 已启动，在任何聊天中输入 -help 以获得帮助消息。
ERROR [2021-12-30 13:58:47] [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xffff98696c10>
INFO [2021-12-30 13:58:48] [pagermaid] 安装失败 dme

INFO [2021-12-30 13:59:26] [pagermaid] 安装失败 dme

INFO [2021-12-30 14:01:05] [pagermaid] 安装成功 : eat

INFO [2021-12-30 14:01:12] [pagermaid] 将平台检测为“linux，进入PagerMaid的早期加载过程。
INFO [2021-12-30 14:01:15] [pagermaid] 设置用户标识成功。 SS(7777777777)
INFO [2021-12-30 14:01:19] [pagermaid] 加载内置模块: account, avoid, captions, clock, external, fun, help, message, plugin, prune, qr, sb, status, sticker, system, update
INFO [2021-12-30 14:01:19] [pagermaid] 加载插件: eat, groupindex, keyword, mjx, paolu, yvlu
INFO [2021-12-30 14:01:20] [pagermaid] Web 界面已禁用。
INFO [2021-12-30 14:01:28] [pagermaid] PagerMaid-Modify 已启动，在任何聊天中输入 -help 以获得帮助消息。
INFO [2021-12-30 14:03:18] [pagermaid] 安装成功 : fuck

**Comment by xtaodada** [comment]
`dme` 已下架，无法安装。
