### ISSUE TITLE
portball 指令存在恶意滥用的问题

### ISSUE THREAD

**Issue by SpriteOvO** [Xtao-Labs/PagerMaid-Modify#34]
### BUG 发生地址
无

### 预期是什么？
我也不知道，也许是以另一种方式显示错误信息或者直接不显示。

### 实际发生了什么？
![image](https://user-images.githubusercontent.com/33660554/99402043-de978c00-2923-11eb-8d20-667270fd56c2.png)
![image](https://user-images.githubusercontent.com/33660554/99403272-3c78a380-2925-11eb-8970-bb3605e4bedc.png)

### 额外信息（日志、报错等）
在群组内发送 -portball 时复现。
严格意义上可能不算是一个 BUG，但的确是一个问题，可能会被他人恶意滥用该指令造成刷屏。

**Comment by Pentacene** [comment]
This issue belong to [PagerMaid_Plugins](https://github.com/Xtao-Labs/PagerMaid_Plugins)
