### ISSUE TITLE
既然tg上不去.那么./.....这样能上去的人是不是就能看到了

### ISSUE THREAD

**Issue by shzxm** [Xtao-Labs/PagerMaid-Modify#36]
既然tg上不去.那么./.....这样能上去的人是不是就能看到了
### 额外描述

**Comment by NonCheng** [comment]
@shzxm ？

**Comment by shzxm** [comment]
> @shzxm？

哇哦.你是谁

**Comment by NonCheng** [comment]
@shzxm 我艹
厉害

**Comment by LovelyHaochi** [comment]
?草?

#有意思

**Comment by shzxm** [comment]
是不是机智如我

**Comment by shzxm** [comment]
我还以为我要被抓走了
或者是97吧tg打爆了

**Comment by LovelyHaochi** [comment]
> 是不是机智如我

嗯

**Comment by NonCheng** [comment]
@shzxm dc1大法好  早日保平安

**Comment by shzxm** [comment]
你们都能上的去么....

**Comment by LovelyHaochi** [comment]
> 你们都能上的去么....

我dc2

**Comment by shzxm** [comment]
卧槽....群里现在还有谁活着

**Comment by LovelyHaochi** [comment]
> 卧槽....群里现在还有谁活着

![image](https://user-images.githubusercontent.com/49602236/101243649-9a3a2780-373c-11eb-95e3-079704205084.png)

**Comment by shzxm** [comment]
这么一出是不是提醒我该弄个dc5之外的号码了

**Comment by shzxm** [comment]
看来....几乎没人在了....

**Comment by LovelyHaochi** [comment]
> 这么一出是不是提醒我该弄个dc5之外的号码了

我就备了个dc2 用上了

**Comment by shzxm** [comment]
你们的号码哪来的

**Comment by LovelyHaochi** [comment]
> 看来....几乎没人在了....

🤔 蛮多人

**Comment by shzxm** [comment]
我去弄一个

**Comment by NonCheng** [comment]
@shzxm gv

**Comment by LovelyHaochi** [comment]
> 你们的号码哪来的



> 我去弄一个

gv或者买

**Comment by shzxm** [comment]
再去买一个gv?????现在还有15r的gv么?

**Comment by LovelyHaochi** [comment]
> 我去弄一个

注册的时候记得别跑亚洲这边的节点

**Comment by LovelyHaochi** [comment]
> 再去买一个gv?????现在还有15r的gv么?

淘宝有 15不转移 20转移

**Comment by shzxm** [comment]
啊?难道是根据节点判断的?

**Comment by LovelyHaochi** [comment]
> 啊?难道是根据节点判断的?

嗯

**Comment by NonCheng** [comment]
@LovelyHaochi 和ip无关

**Comment by LovelyHaochi** [comment]
> 啊?难道是根据节点判断的?

注册时的节点

**Comment by shzxm** [comment]
我现有的账号里边能不能有多个gv号码?

**Comment by LovelyHaochi** [comment]
> 我现有的账号里边能不能有多个gv号码?

nope

**Comment by shzxm** [comment]
那....b了

**Comment by shzxm** [comment]
![Uploading EhQDdWiUwAA1Jdg.jpg…]()

**Comment by LovelyHaochi** [comment]
> 那....b了

dc5部分开始恢复 我分组回来了

**Comment by shzxm** [comment]
你们能看到这个么?

**Comment by LovelyHaochi** [comment]
> 你们能看到这个么?

你先上传再发

**Comment by NonCheng** [comment]
@LovelyHaochi no github
tg plz

**Comment by NonCheng** [comment]
@shzxm 我邮箱炸了

**Comment by shzxm** [comment]
我分组是好的.但是看不到群里

**Comment by shzxm** [comment]
邮箱为什么会炸

**Comment by LovelyHaochi** [comment]
> @shzxm 我邮箱炸了

hhhhhhhhc 他dc5

**Comment by Pentacene** [comment]
我邮箱炸了，各位。

**Comment by shzxm** [comment]
等下....issus能删除不?

**Comment by shzxm** [comment]
工具人都出来了

**Comment by shzxm** [comment]
> 我邮箱炸了，各位。

爱你

**Comment by shzxm** [comment]
会不会保存到北极去.这些对话

**Comment by gchengyu** [comment]
@shzxm 可能会

**Comment by shzxm** [comment]
北极代码库会保存issue么.

**Comment by shzxm** [comment]
![Uploading image.png…]()

**Comment by LovelyHaochi** [comment]
去 #37

**Comment by shzxm** [comment]
我还是这个界面

**Comment by shzxm** [comment]
![image](https://user-images.githubusercontent.com/9905297/101243799-9064f400-373d-11eb-8d0e-4102e2fb20a2.png)
xtao锁了

**Comment by shzxm** [comment]
我还是上不去.xtao我想你了.爱你

**Comment by NonCheng** [comment]
@shzxm 恶心心

**Comment by shzxm** [comment]
> @shzxm恶心心

你的title就是爱我.你还说我?

**Comment by NonCheng** [comment]
@shzxm ？

**Comment by shzxm** [comment]
> @shzxm？

你自己看啊

**Comment by jiuqi9997** [comment]
github竟然变成聊天地

**Comment by shzxm** [comment]
啊.97是不是你打的

**Comment by NonCheng** [comment]
@shzxm ？

**Comment by jiuqi9997** [comment]
是你吧，绝对是你吧

**Comment by shzxm** [comment]
> 是你吧，绝对是你吧

被你发现了.我以为再也见不到你们了

**Comment by jiuqi9997** [comment]
> > 是你吧，绝对是你吧
> 
> 被你发现了.我以为再也见不到你们了

怎么会变成这样
