### ISSUE TITLE
Docker container内redis还是不启动...

### ISSUE THREAD

**Issue by clatteringmarion** [Xtao-Labs/PagerMaid-Modify#46]
### BUG 发生地址
Docker container 最新镜像， 安装并启动后`-status` redis数据库会显示未连接
### 预期是什么？
`-status`显示数据库已连接
### 实际发生了什么？
`-status`显示数据库未连接， redis已安装但是未启动
### 额外信息（日志、报错等）
> $ systemctl status redis
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

> $ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> 

Host OS: Ubuntu 20.04
Container OS: 
> $ sudo cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

generated by github-issue-template
-->

**Comment by clatteringmarion** [comment]
Pull了一下，看着还是获取的老的image... 不太清楚为毛 （用digest和latest都是同样输出...）
> $ docker pull mrwangzhe/pagermaid_modify@sha256:813d36a52bf6d401df4ec6c717ad7f104102d769b41d9670d03cf597dc529cc9
docker.io/mrwangzhe/pagermaid_modify@sha256:813d36a52bf6d401df4ec6c717ad7f104102d769b41d9670d03cf597dc529cc9: Pulling from mrwangzhe/pagermaid_modify
43b7db9b6cef: Pull complete 
65607e2592bb: Pull complete 
7e0470ece347: Pull complete 
ed64886237d5: Pull complete 
ef50197a8bdc: Pull complete 
417781cbd1a1: Pull complete 
d2e91b54e157: Pull complete 
dc9b3f8ca0e0: Pull complete 
d07326157acb: Pull complete 
Digest: sha256:813d36a52bf6d401df4ec6c717ad7f104102d769b41d9670d03cf597dc529cc9
Status: Downloaded newer image for mrwangzhe/pagermaid_modify@sha256:813d36a52bf6d401df4ec6c717ad7f104102d769b41d9670d03cf597dc529cc9
docker.io/mrwangzhe/pagermaid_modify@sha256:813d36a52bf6d401df4ec6c717ad7f104102d769b41d9670d03cf597dc529cc9

> $ docker image ls
REPOSITORY                    TAG         IMAGE ID       CREATED        SIZE
mrwangzhe/pagermaid_modify    <none>      17ebac441fd1   3 months ago   2.05GB

**Comment by xtaodada** [comment]
非项目问题。

**Comment by c3b2a** [comment]
@pagermaid-bot[bot] .cn 草

**Comment by NonCheng** [comment]
@pagermaid-bot[bot] @mrwangzhe 
这玩意是你上次修docker没修完的锅

**Comment by clatteringmarion** [comment]
@NonCheng  不是不是, 好像是我本地Docker的锅
Docker拉下来的镜像是好几个月以前的那个(Redis有问题的)... 不知道肿么回事 (明明其他的都是能用的)
