### ISSUE TITLE
Docker 环境下如何安装额外 pypi 包

### ISSUE THREAD

**Issue by Dellear** [Xtao-Labs/PagerMaid-Modify#62]
开始出现 执行python3 pip install 安装时 No module named 'pip'，这个问题google解决了，然后执行python3 -m pip install dateparser又出现了如下报错
![image](https://user-images.githubusercontent.com/22325851/114909346-a2734380-9e4f-11eb-870b-0fd035f7f407.png)

**Comment by xtaodada** [comment]
亲 这不是报错，这就是已经安装过的提示。

**Comment by xtaodada** [comment]
Docker 采用虚拟环境运行，安装额外 pypi 包请使用

```
/pagermaid/workdir/venv/bin/python -m pip install [name]
```
