### ISSUE TITLE
集成在Telegram中删除账户所加入的超级群组的所有消息功能

### ISSUE THREAD

**Issue by opz20** [Xtao-Labs/PagerMaid-Modify#76]
集成在Telegram中删除账户所加入的超级群组的所有消息功能

https://github.com/hannesveit/telegram-delete-all-messages/blob/a6ce4f34c21e7f6d037ad72f35441d546bad6bfb/cleaner.py
有人做了个分支出来了，可以参考集成一下？

**Comment by Pentacene** [comment]
@opz20 This feature may published as plugin next week.

**Comment by Pentacene** [comment]
Xtao-Labs/PagerMaid_Plugins#161
