### ISSUE TITLE
管理群组的脚本

### ISSUE THREAD

**Issue by ShadowsSide** [Xtao-Labs/PagerMaid-Modify#83]
### 这是一个什么样的功能？
回复某个用户或提及某人时,可以将他封禁并删除他所有的历史消息,并将他的群内4个权限全部关闭.

### 这个 feature 可以干什么？
部分群组机器人只能单独封禁用户,但不会删除他所有的历史消息.需要额外手动删除

### 额外描述
最好能自定义群组ID,并接受其他admin发出该指令.

**Comment by Pentacene** [comment]
Xtao-Labs/PagerMaid_Plugins#169
