### ISSUE TITLE
1，复读 / 2，自动抽奖

### ISSUE THREAD

**Issue by Lunatic-Scarlet** [Xtao-Labs/PagerMaid-Modify#94]
### 这是一个什么样的功能？
1，复读
2，自动抽奖

### 这个 feature 可以干什么？
1，复读
2，自动抽奖
### 额外描述
1，例：设置的群，同类3条以上自动复读
2，例：设置的群，抽奖bot发布抽奖信息，自动抓取口令发送。

**Comment by xtaodada** [comment]
复读已上线，请安装 `repeat` ，自动抽奖违反抽奖本意，无相关计划。
